import { Inter } from "next/font/google";
import HeaderAppBar from "./components/header/header-app-bar";
import "./globals.scss";
import getSessionData from "@/app/utils/get-session-data";
import getUserData from "./utils/get-user-data";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

 

export default async function RootLayout({ children }) {
  let sessionData = null;
  try {
    sessionData = await getSessionData();
  } catch(error) {
    sessionData = null;
  }
  const userData = sessionData ? await getUserData({sessionData}) : null;
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderAppBar user-data={userData}/>
        {children}
        </body>
    </html>
  );
}
